### ISSUE TITLE
to-juicer (INFO Writing pairs slow)

### ISSUE THREAD

**Issue by saraebell** [vaquerizaslab/fanc#102]
I am trying to process raw fastq file from Hi-C experiments in hopes of doing feature annotation and analysis with Juicer Tools (arrowhead). I have been able to use most fanc commands (map, sort-sam, and pairs) without any issues until I get to **fanc to-juicer**. The job does not run past **INFO Writing pairs** . I am on a university HPC running CentO7 and I use salloc to allocate resources and submit a job for execution (48 hour max). The CPU% is low when checked, around 1-3%. I have attached some screen shots for reference. I would appreciate any suggestions on getting the juicer hic files generated. Or at least if I am running the command correctly. Thank you in advance.   

![fanc to_juicer](https://user-images.githubusercontent.com/82554600/158895562-9106c5eb-5f0a-42c2-88be-cdd490db8d60.png)
![CPU%](https://user-images.githubusercontent.com/82554600/158895588-eddaf32c-ab0a-47ae-9dbc-af5dcf49997e.png)

**Comment by kaukrise** [comment]
Hi, 

your command looks fine to me. 

Since you are using a computational cluster, odds are that the I/O operations are taking place on a networked file system. I/O operations might be slow due to this.

Since we have a similar situation at our institute, I implemented a parameter for most `fanc` commands that copies all input files and writes all output files to the local file system for the duration of the command, and copies output files to their final destination after completion. This can really speed up runtime, especially when your temporary folder is located on an SSD, for example. To enable it, simply append the `-tmp` flag to your command. For this to be effective, please ensure that your system's temporary directory points to a local folder, or manually set the `TMPDIR` environment variable (see [here](https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp) for details).

Additionally, I made a modified version of `fanc` with the following changes:

- There is now a progress bar on the `Writing pairs` step, which should at least give you an idea if the command is progressing or stuck entirely
- There is now an option to write pairs to an uncompressed intermediate file (`--no-gzip`). This will potentially also speed up the I/O, but at the cost of (temporary) disk space. Please make sure you have sufficient space on disk before enabling this flag, especially when using it in combination with `-tmp`!

[fanc-0.9.23b2.tar.gz](https://github.com/vaquerizaslab/fanc/files/8302934/fanc-0.9.23b2.tar.gz)

**Comment by saraebell** [comment]
Thank you for all the helpful information! I am running the command with the added -tmp parameter to see if it resolves this issue. 

Having the progress bar would be great, is there a way to also use pip install fanc to install/update to the modified version and replace the current fanc version I have? Or if I download and uncompress the tar.gz where should I cd into to **execute the fanc to-juicer** command (ie bin, docs, docsrc, fanc)? Thank you again!

**Comment by kaukrise** [comment]
Hi, just do

```
pip install fanc-0.9.23b2.tar.gz
```

directly on the downloaded file! No need to extract anything.

**Comment by saraebell** [comment]
Thank you, I was able to successfully update to the modified fanc version.

It appears the progress bar on the **Writing pairs** step estimated 3+ days (which is more than the time parameter allows for gpu nodes). 
Is there any other recommendation? 
Currently I am going to switch to a smaller fastq file data set around (5GB per fastq file) and see how fanc to-juicer works **after** going through the map, sort-sam, and pairs commands. 

Additionally, I tried to use **fanc map** with the -tmp on some different fastq files but I get this error message
**OSError: [Errno 28] No space left on device:** 
The fastq file is about 20GB. What would be an appropriate solution? 
I did not get this issue without the -tmp parameter before (ie **before I updated to the modified fanc version**). 
![Screen Shot 2022-03-18 at 11 15 02 PM](https://user-images.githubusercontent.com/82554600/159129086-2e7d8643-f388-4ad3-b20f-b51e8d29a5d7.png)


Thank you again, your continuous support is great appreciated!

**Comment by saraebell** [comment]
It appears I am getting more issues now than before (with a smaller dataset)
![Screen Shot 2022-03-19 at 9 16 40 AM](https://user-images.githubusercontent.com/82554600/159129272-7d38ed69-cb66-4755-80ec-214bfbd9997b.png)
![Screen Shot 2022-03-19 at 9 16 53 AM](https://user-images.githubusercontent.com/82554600/159129290-ce7ecfa0-f769-4960-b2c4-7d9f94a194c9.png)

**Comment by saraebell** [comment]
I decided to uninstall the modified version fanc-0.9.23b2 and reinstall fanc-0.9.22 due to the fact that I am getting errors that I did not have with fanc commands (map, sort-sam, pairs).

I have check that the version I now have is back to fanc-0.9.22 (ie fanc --version) but these files (I believe tmp files) are still being generated even though **I am not using the -tmp parameter**, which this did not happen when I originally installed fanc-0.9.22 and I keep getting the same **issues as above with fanc map** which was never an issue before. 

What exactly is in these files? Again, thank you for your time. 
![Screen Shot 2022-03-19 at 10 48 05 AM](https://user-images.githubusercontent.com/82554600/159133061-b2727be0-ecfb-4409-9e5d-2d9ea279cf43.png)

**Comment by kaukrise** [comment]
Hey, I'm sorry, I don't have much time this weekend, but it appears as though you are simply running out of disk space on the computing node.
You can delete those temporary files - they are part of fanc and are likely left from the failed run earlier. fanc map was not altered in the new beta version.

The progress bar time estimate is not reliable, as it counts chromosome pairs, and starts off with the largest chromosomes. It will be faster than 3 days.

**Comment by saraebell** [comment]
I already deleted those temporary files the issue now is when I run **fanc map without the -tmp parameter** new ones get generated, but I assume they are only generated with -tmp. 
So I am confused why after I deleted the temporary files multiple times they get regenerated if I am not using -tmp for fanc map.

**Comment by kaukrise** [comment]
tmp files are always generated in `fanc map`. `-tmp` merely avoids most network I/O. So what you are seeing is expected behaviour. 

Nonetheless `OSError: [Errno 28] No space left on device` clearly indicates you ran out of disk space on the computing node. If this is still an issue, you can set the `TMPDIR` environment variable to a folder on a drive with more space.

**Comment by saraebell** [comment]
Thank you so much for all your help! I set --mem=236GB and ran the job on a GPU node, which appeared to fix the issues I was having with **fanc map**. I also believe there was an issue when I originally installed HDF5, so I re-installed it and used --prefix to install HDF5 in my conda environment (I did not see it there before until I reinstalled). Not sure if that was related. 

I believe I have successfully ran the to-juicer command, I tested **fanc to-juicer** with a single .pairs file and it finished quick (~ 5 mins). I have attached a screen shot below. Would you be ale to confirm that the job was completed correctly/successfully. A .hic file was generated but I did notice the following warning: 
_No resolution chosen for Juicer Hic - using 10000bp. Specify a custom resolution using <.hic file>@<resolution>
  warnings.warn("No resolution chosen for Juicer Hic - using {}bp. "_

I set the resolution with **-r 10000** as follows: 
salloc -p gpu --gres=gpu:1 --mem=236GB --time=0-48:00:00 fanc to-juicer pairs_out/dm3/s2/2291.pairs juicer_hic_out/dm3/s2_2291_jui.hic --juicer-tools-jar /home/014843907/tools/juicer/juicer_tools_1.22.01.jar -r 10000

![Screen Shot 2022-03-20 at 5 46 00 PM](https://user-images.githubusercontent.com/82554600/159193334-a6c22416-12d8-47ff-af36-3595e1c59925.png)

**Comment by kaukrise** [comment]
Hi again,

the warning you received about resolution can safely be ignored. This is just FAN-C testing that the Juicer file can be loaded.

However, 5 minutes seems really fast, and it makes me doubtful that the command completed successfully. It did a quick back of the envelope calculation and on my machine: `to-juicer` should be able to process ~0.5 to 1 million pairs per minute. I don't know how many valid pairs you have, though, and it is possible that your command really was that fast in the end.

You should try to plot the matrix! You can either use FAN-C (for example using the `fancplot` command line utility for a [quick plot](https://fan-c.readthedocs.io/en/latest/fancplot-executable/matrix_panel_types.html)), or import into [Juicebox](https://github.com/aidenlab/Juicebox/wiki/Download).

**Comment by saraebell** [comment]
Thank you again for all the continuous support! I was able to successfully generate the juicer .hic files and use arrowhead from Juicer Tools to find contact domains. Closing this issue.

**Comment by kaukrise** [comment]
As you can see from the logging output, the estimate of 21 days is based on a single iteration of the writing pairs loop. It is highly likely that this will adjust itself to something more reasonable. If it does not, running the command on an SSD (see https://fan-c.readthedocs.io/en/latest/fanc-executable/fanc_basic.html#temporary-files) will speed things up. Otherwise my only suggestion would be to run it locally and not on the cluster.

**Comment by saraebell** [comment]
I believe the GPU node I requested is equipped with a solid state drive. Thank you for the information and recommendation. Closing issue now.
