### ISSUE TITLE
invalid value encountered in true_divide

### ISSUE THREAD

**Issue by JhinAir** [vaquerizaslab/fanc#12]
Hi,

After obtaining .hic file, finc would throw out such warnings as below, when calling AB compartment.
![image](https://user-images.githubusercontent.com/28035521/75263776-bba1d680-57ee-11ea-9ac2-fc1f177911e9.png)
I am not sure what it would influence. And for the AB domains, I found all the scores of domains are negative value, no matter what type they are assigned. How could it be?
My command is : fanc compartments 40Kb.ZW.hic 40Kb.ZW.AB.matrix -d 40Kb.ZW.AB.domain -v 40Kb.ZW.AB.ev.txt -g ZW.fa -w -e 40Kb.ZW.AB.profile.png -p 10 20 30 40 50 60 70 80 90 100

Best~
Jing

**Comment by kaukrise** [comment]
Hi,

the warnings are generated by Numpy whenever a division produces NaN, such as dividing by 0. In this case they can be safely ignored, as NaN are properly handled by the command. I am silencing these warnings in the future.

Regarding the other issue, there was a bug in the domain calculation code, which I have fixed in the latest version (`0.8.24`). Could you please upgrade your FAN-C version and repeat the compartment analysis? 

Also, are you certain you want to run the compartment analysis with the `-w` argument? It most likely is not a correct setting for your analysis, especially if your matrices have been produced using the standard FAN-C pipeline or Juicer. See [here](https://github.com/vaquerizaslab/fanc/issues/10#issuecomment-587405281) for an explanation and note that the help text for `-w` includes a warning regarding this.

If the issue persists despite updating, could you please post the following?

- The output of `fanc -V`
- The profile plot generated with `-e`
- The first 20 or so lines of the file with domain scores

Thank you!

**Comment by JhinAir** [comment]
Yes, with -w argument, I will get errors. After removing this, fanc can output final results. Regardless of the previous negative value issue, the AB calling seems not right, as almost all the windows for each chromosome are assigned with the same type "A" or "B", like the example below.

**Comment by jmsanper** [comment]
Maybe your 1st eigenvector is capturing chromosome arms, try the second eigenvector with '-i 2'.
Best,
Jose Maria

**Comment by kaukrise** [comment]
@jmsanper this is really good advice, we have seen that lot in our data. I am closing this now due to inactivity from the OP.
