### ISSUE TITLE
Error when normalizing capture HiC data.

### ISSUE THREAD

**Issue by joshuak94** [vaquerizaslab/fanc#137]
Hello! I'm encountering the following error when normalizing binned capture HiC data. It seems it doesn't happen with every bin size. In my case, the captured region is ~4 Mb large on chromosome 18 of the mouse genome. The error seems to occur with bin size 50kb and smaller. Larger bin sizes (100kb, 250kb, etc.) don't cause any error. Despite the error, files are generated for all bin sizes, though I guess those which produce errors are not normalized.

```sh
Traceback (most recent call last):
  File "/home/user/.local/bin/fanc", line 127, in <module>
    Fanc()
  File "/home/user/.local/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/home/user/.local/lib/python3.8/site-packages/fanc/commands/fanc_commands.py", line 1634, in hic
    binned_hic.normalise(norm_method, whole_matrix=whole_matrix,
  File "/home/user/.local/lib/python3.8/site-packages/fanc/hic.py", line 427, in normalise
    bias_vector = kr_balancing(self, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/fanc/hic.py", line 876, in kr_balancing
    m_corrected, bias_vector_chromosome = correct_matrix(m, restore_coverage=restore_coverage)
  File "/home/user/.local/lib/python3.8/site-packages/fanc/hic.py", line 921, in correct_matrix
    raise RuntimeError("Exceeded maximum attempts (%d)" % max_attempts)
RuntimeError: Exceeded maximum attempts (50)
```

I also run into a similar issue when calculating the insulation score:
```sh
Traceback (most recent call last):
  File "/home/user/.local/bin/fanc", line 127, in <module>
    Fanc()
  File "/home/user/.local/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/home/user/.local/lib/python3.8/site-packages/fanc/commands/fanc_commands.py", line 3792, in insulation
    _domain_scores(parser, input_file, output_file, output_format,
  File "/home/user/.local/lib/python3.8/site-packages/fanc/commands/fanc_commands.py", line 3844, in _domain_scores
    scores = score_class.from_hic(matrix, file_name=output_file,
  File "/home/user/.local/lib/python3.8/site-packages/fanc/architecture/domains.py", line 342, in from_hic
    values_by_chromosome[w_ix][k] /= bin_window_size ** 2
ZeroDivisionError: division by zero
```

I guess these errors are caused because capture HiC only results in a specific region being sequenced, so the rest of the genome has no reads. The second issue may also be related to the first issue, since maybe running the insulation command on an unnormalized file causes unwanted behavior. Do you have any suggestions on how to proceed/bypass these issues?

**Comment by joshuak94** [comment]
I'm currently trying what was mentioned in #66. Will let you know if this works!

**Comment by kaukrise** [comment]
Hi, FAN-C was not designed for capture Hi-C specifically, but there might be workarounds for your problems. 

1. KR balancing runs into trouble when the matrix is extremely sparse. Maybe try the `-m ICE` parameter, which switches the normalisation to iterative matrix balancing. However, one of the assumptions of both KR and ICE balancing is equal bin coverage, which I suppose is violated in the case of capture Hi-C? I am sure there are more appropriate normalisation methods in a different package that would work better.
2. Regarding the insulation score: the error you posted implies that `bin_window_size` is `0` - since this is just the insulation window size expressed in number of bins, I am wondering if you are selecting a window size that is smaller than the matrix resolution. Can you please post your matrix resolution and the full command you used here? As a general note: the default normalisation (division by chromosome mean) is probably not what you want for your data, since the majority of the insulation scores will be `0`. Again, these functions are not designed for capture Hi-C data.

**Comment by joshuak94** [comment]
The full commands were as follows:

`fanc hic hic_file.hic binned/5kb.hic -b 5kb -a -n -m KR -f -t 16`
and
`fanc insulation binned/5kb.hic 5kb.insulation -w 50kb 100kb 250kb 500kb 1mb -r chr18:53656551-57425762 --normalisation-window 1 -o bed -i`

Thanks for the info and quick response!

**Comment by kaukrise** [comment]
In the insulation command, `--normalisation-window <n>` means that each insulation score value will be divided by the mean insulation in a window of `<n>` bins, surrounding each bin. In your case, `--normalisation-window 1` would divide the value by itself.

Also, please do not use `-i`. I would not recommend it in general, but in your case specifically it does not make sense, because the imputation replaces missing values with the expected value at that distance. This is calculated from all values, which in your case are mostly missing due to the capture Hi-C.

Please try the following command first - if that still causes trouble we'll check other error sources:

```bash
fanc insulation binned/5kb.hic 5kb.insulation -w 50kb 100kb 250kb 500kb 1mb -r chr18:53656551-57425762
```
