### ISSUE TITLE
qname_ix missing

### ISSUE THREAD

**Issue by jessakay** [vaquerizaslab/fanc#16]
Thank you for developing this fantastic library bringing together so many useful functions! I'm looking to use it for only alignment / filtering pairs at the moment and did the following:
```
fanc map ${samp}_R1.fq.gz $REF/bowtie2_index/mm10 ${samp}_R1.sam -t 48 -r DpnII
fanc map ${samp}_R2.fq.gz $REF/bowtie2_index/mm10 ${samp}_R2.sam -t 48 -r DpnII
samtools sort -@ 47 -n -o ${samp}_R1.bam ${samp}_R1.sam
samtools sort -@ 47 -n -o ${samp}_R2.bam ${samp}_R2.sam
fanc pairs -g $REF/bowtie2_index/mm10.fa \
  -r DpnII -q 30 -t 48 -p 2 -d 500 -i 1000 \
  -f -l -m -us \
  ${samp}_R1.bam \
  ${samp}_R2.bam \
  ${samp}.pair
```

I then proceeded to use the python API to look at the ouput:
```
import fanc
p = fanc.load('out.pair')
```

But the likes of `p[0].left.qname_ix` and `p[0].right.qname_ix` all return `None`. Is this intended? How can I make sure that attribute is assigned in the constructor?

Since my goal is to actually obtain the set difference between two `pair` files (same set of filters except one also have a uniqueness filter and one does not, to specifically take multi-mapping pairs) the qname or its index is critical.

Though I did find that the parent FragmentReadPair objects do contain a valid 'ix' attribute, but I couldn't figure out what it is from the documentation. Should this also correspond to the read name?

**Comment by kaukrise** [comment]
Hi, and thanks for using FAN-C!

Unfortunately, the `qname_ix` property is a remainder from when read pairs were handled differently by FAN-C. We no longer keep track of the `qname`, because for most applications this isn't necessary, and it takes a lot of space on the disk. The other `ix` is just an auto-incrementing index.

Maybe we can come up with an alternative way to solve your issue, though. Do you want to only keep read pairs where *both* reads are multimapping, or also those where one read is unique and the other is multimapping?

**Comment by kaukrise** [comment]
One straightforward way to do it would be to generate two SAM/BAM files as input that only contain read pairs you want (i.e. either one or both multimapping).

Since you are already using the API, here is a solution that uses FAN-C for the read pairing and filtering, and then pysam to write two new BAM files that you can use as input to `fanc pairs`:

```python
import pysam
from fanc.pairs import SamBamReadPairGenerator, UniquenessFilter


sam1_file = "sam/SRR4271982_chr18_19_1_sort.bam"
sam2_file = "sam/SRR4271982_chr18_19_2_sort.bam"

filtered_sam1_file = "sam/SRR4271982_chr18_19_1_sort_multi.bam"
filtered_sam2_file = "sam/SRR4271982_chr18_19_2_sort_multi.bam"

f = UniquenessFilter(strict=True)

pair_generator = SamBamReadPairGenerator(sam1_file, sam2_file, check_sorted=False)

with pysam.AlignmentFile(sam1_file) as sam1:
    with pysam.AlignmentFile(sam2_file) as sam2:
        with pysam.AlignmentFile(filtered_sam1_file, template=sam1, mode='wb') as out1:
            with pysam.AlignmentFile(filtered_sam2_file, template=sam2, mode='wb') as out2:
                for read1, read2 in pair_generator:
                    # keep pairs where at least one is multimapping. Replace the following 
                    # "or" by "and" to only keep pairs with two multimapping reads
                    if not f.valid_read(read1) or not f.valid_read(read2):  
                        out1.write(read1)
                        out2.write(read2)

```

This uses the FAN-C sample data, where I tested this on. Since you are using SAM, not BAM files, you probably have to change the `mode='wb'` to `mode='wh`, if I remember correctly. Otherwise convert your files to BAM before running this.

I hope this helps!

**Comment by jessakay** [comment]
Oh that's exactly what I need! Thank you for the fast response. I wanted to have one file with all the pairs with at least one multi-mapper and another with only unique-unique pairs.

However, I'd also like to track all the multi-mapping pair permutations by read name. For instance: given a pair of sequences named `X` with the forward read mapping to `m` positions and reverse to `n`, assuming all these alignments pass the specified filters, I'd like to have a way of obtaining `m` x `n` pairs (should be already possible if I don't specify an uniqueness filter on the multi-mapping BAM?) and know that they all originated from read `X` (not sure how to do this if qname is not tracked). Would this be achievable using `fanc pairs`?

**Comment by kaukrise** [comment]
Sorry, but there isn't anything that would be directly usable in FAN-C for this. I would recommend an approach using `pysam`, where you iterate over the reads in both sorted SAM files simultaneously. This is what FAN-C also does internally, for example in `SamBamReadPairGenerator`. Maybe you will find some inspiration [in the corresponding code section](https://github.com/vaquerizaslab/fanc/blob/0913148b4414050d915803a2bea91afbf94455ca/fanc/pairs.py#L867) - you might be able to modify it to your needs. Good luck!

**Comment by jessakay** [comment]
I see! Thanks for your help, the tips were very useful!
