### ISSUE TITLE
email notification

### ISSUE THREAD

**Issue by tereski** [vaquerizaslab/fanc#20]
I have trouble with email notification (fanc 0.8.32). I do not get it after a process is finished. This is what I wrote in fanc.conf file.

```
#
# EMAIL
#
email_from_address: XXX@gmail.com
email_smtp_server: smtp.gmail.com
email_smtp_port: 587
email_smtp_username: XXX
email_smtp_password: YYY

```
What is the best way to test email notifications?

**Comment by kaukrise** [comment]
Hi again,

First of all, you need to use the `-m email@address.com` (substitute your address) command, if you don't do that already. Put it right after `fanc`.

Since you are using Gmail you will need to enable less secure access in your security settings. I recommend a separate email address than your main one!

I also sometimes had issues sending to the same email as the from address. Again, I recommend using a separate account.

Cheers,
Kai

**Comment by tereski** [comment]
Thank you, now email notification is working.

Cheers,
Teresa
