### ISSUE TITLE
how to handle multiple replicates in fanc auto option?

### ISSUE THREAD

**Issue by Drosophilid** [vaquerizaslab/fanc#24]
I have 3 different replicates of the same sample and want to use them together. if possible in fanc auto option? 

I tried to write command as: 
fanc auto R1.read1.fastq.gz,R2.read1.fastq.gz,R3.read1.fastq.gz R1.read2.fastq.gz,R2.read2.fastq.gz,R3.read2.fastq.gz

but it didn't work this way.

Thanks!

**Comment by kaukrise** [comment]
Hi again!

This is demonstrated on [this page of the docs](https://vaquerizaslab.github.io/fanc/fanc-executable/fanc-generate-hic/fanc_auto.html#mixed-input). The syntax would be

```
fanc auto <parameters> R1.read1.fastq R1.read2.fastq R2.read1.fastq R2.read2.fastq R3.read1.fastq R3.read2.fastq output_folder/
```

and so on. All input is separated by spaces, mates follow each other.

However, I would recommend another strategy. Process each of the replicates separately with `fanc auto`, so that you can inspect the individual matrices. Then merge the fragment-level Hi-C files (those in each replicate's `hic` folder):

```
fanc auto <parameters> R1/hic/r1.hic R2/hic/r2.hic R3/hic/r3.hic output_folder/
```

Both are valid approaches, but in the second one you get binned and normalised matrices also for the replicates, which are often useful for quality control, for example.

**Comment by Drosophilid** [comment]
Thanks Kai, may be I'll follow the second suggestion, to create the Hi-C for each replicate separately and then merge them.
Thanks again
