### ISSUE TITLE
Questions about TAD calling

### ISSUE THREAD

**Issue by Rseq** [vaquerizaslab/fanc#27]
Hi, 

First, I would like to thank you for developing FANC tools and make it available.
It is helpful and it made simpler to analyse Hi-C data. 
However, I'm once again asking for your help.

I intend to perform TAD calling and I would like to know what is the difference between `fanc boundaries` and `tadtool`.
It was not clear for me in this statement if `fanc boundaries` is a 1-TAD caller algorithm itself or 2-calls `tadtool`

> We are therefore currently not bundling a TAD calling tool with FAN-C, and refer the user to one of the many available tools for TAD calling that offer a wide range of features. [https://vaquerizaslab.github.io/fanc/fanc-executable/fanc-analyse-hic/domains.html#a-note-on-tad-calling](https://vaquerizaslab.github.io/fanc/fanc-executable/fanc-analyse-hic/domains.html#a-note-on-tad-calling)

In case it is option 1- a TAD caller algorithm itself, which one has performed better on your hands?

Thank you for your time

**Comment by kaukrise** [comment]
Hi, thank you for your question.

`fanc boundaries` is not a TAD caller. It calls insulating boundaries - individual bins with a strong insulating potential, i.e. comparatively few contacts spanning them. TADs are **domains** which are delineated by those boundaries. As stated in the documentation quote you linked to above, FAN-C does not come bundled with a TAD caller, and it also does not call TADtool.

TADtool uses the same algorithm to call insulating boundaries, and then has an additional step where it determines if any region between two boundaries has sufficient signal enrichment above background to be a TAD.

TAD calling is very sensitive to parameter choices (insulation score window size, boundary strength cutoff, matrix resolution, etc), and also depends on the types of TADs you are interested in (large domains, nested domains). Therefore we have written TADtool, which allows you to find robust parameter ranges visually. However, our work has recently focused more on TAD boundaries, or the insulation score around genomic elements of interest, than TADs themselves.

When you want to work with TADs directly, I would advise you to use multiple of the many available TAD callers, preferably with different algorithms, and get a robust consensus set of domains. Otherwise, depending on your question, it may be preferable to work with the insulation score directly, rather than the domains.

I hope this is helpful!

**Comment by Rseq** [comment]
Thank you for your prompt reply.
It was quite helpful! I misunderstood it, that is why I did this confusion..
However, please correct me:
 If
> FAN-C provides multiple “scores” that are designed to find the boundaries between domains. [https://vaquerizaslab.github.io/fanc/fanc-executable/fanc-analyse-hic/domains.html#hi-c-domain-analysis](url)
Then, once one knows the boundaries, would not be TADs what is in-between?

I believe that for my aim, to check if there is a difference in TAD borders among different conditions, the insulating boundaries are even better. 

Thank you again!

**Comment by kaukrise** [comment]
> Then, once one knows the boundaries, would not be TADs what is in-between?

Consider these examples:

```
              /\
       /\    /##\
      /##\/\/####\/\
TADs: --- -- ---- --
      
       /\
      /##\________/\
TADs: ---         --
```

In the first one, the TADs are indeed all regions between boundaries. However, there are often large genomic regions with weak or no discernible structure between boundaries. I suppose it is a matter of definition if you want to call them TADs or not, but this is why TADtool requires a minimum level of signal between boundaries before a TAD is called.

**Comment by Rseq** [comment]
> I suppose it is a matter of definition if you want to call them TADs or not

I agree with this concept if one considers the in-between in the second example as unique-extended boundaries

> TADtool requires a minimum level of signal between boundaries before a TAD is called

However, my perception is closer to this as well

Thank you again for your time and clarification!
All my best
