### ISSUE TITLE
issue to separate AB domains

### ISSUE THREAD

**Issue by Drosophilid** [vaquerizaslab/fanc#28]
Hello, I was trying to seperate the AB domains using command: 

fanc compartments -d domains.gc.bed -g genome.fa sample.ab
(using fanc version: 0.9.3)
But the distribution of AB domains looks not normal (image attached). could you please help to resolve this issue.

![Screen Shot 2020-11-01 at 12 48 51 AM](https://user-images.githubusercontent.com/64106867/97792251-4176ec80-1bdc-11eb-8642-b0cdf161753b.png)

Thanks

**Comment by Drosophilid** [comment]
Thanks for your reply @kaukrise,
Here is AB correlation matrix with eigenvector.
![test](https://user-images.githubusercontent.com/64106867/97799161-8d518200-1c2c-11eb-81d8-d02a705a766b.png)

The thing that not looks normal to me, is the no of A and B domains (A=93 and B=94 in chrX), that I don't expect. How is its possible that one bin is A and second bin is B, and this pattern is consistent throughout the chromosomal length. Even in the given example we can see the normal distribution of AB domains.
![Screen Shot 2020-11-01 at 10 31 24 AM](https://user-images.githubusercontent.com/64106867/97799298-97c04b80-1c2d-11eb-841e-a03a941114e5.png)

**Comment by kaukrise** [comment]
Sorry, the example file in the docs is wrong, thanks for finding that. However, the documentation text is correct:

>The output contains the domain type in the “name” field and the average eigenvector entry values of all bins in the domain in the “score” field.

The domains BED file merges all consecutive bins in the same domain, which is why A and B are always alternating. Please have a look at the start and end coordinates for each entry in the BED. They do not correspond to bin sizes, but are multiples thereof.

You will see what that looks like with the bar plot I mentioned above.

**Comment by Drosophilid** [comment]
I got it thanks @kaukrise

**Comment by kaukrise** [comment]
I have updated the docs with the correct domain output.
