### ISSUE TITLE
How to deal with lots of contigs?

### ISSUE THREAD

**Issue by balwierz** [vaquerizaslab/fanc#3]
```hic.py:268: UserWarning: Number of chromosomes (1061) is very large. Consider limiting the processed chromosomes using the 'chromosomes' argument or expect significant slowdown during binning!```

There are chromosomes in the assembly + 1000 of contigs (up to 1Mb, but mostly shorter)
Isn't binning time linear with the total length of chromosomes/contigs? (Or quadratic if it means contact binning). 
Or should I really worry about this warning message? If yes, then how do you recommend running the pipeline?

**Comment by balwierz** [comment]
And can the option `--chromosomes CHROMOSOMES` be passed to `auto` so it is used within `hic` commands later?

**Comment by kaukrise** [comment]
Binning in this case refers to the assignment of contacts to bins, not the partitioning of chromosomes into equi-distant regions. The way binning is parallelised is by chromosome pair, so in the worst case the slowdown is quadratic.
Most of the time small contigs add little insight due to Hi-C resolution, so in the documentation we recommend using a "cleaned up" genome. You can use the `fanc fragments` helper function to build something like this (check out the `--chromosomes` option). Use that genome version next time for the `-g` argument in `fanc auto`.

Currently this is not an option for `fanc auto`, but I'll consider adding it in the future. It is an option for `fanc hic`, however, so you can bin and normalise using

```
fanc hic --chromosomes <chr1> <chr2> <...> -b <bin size> -k <fragment level hic> <hic output>
```

Check out the help, too, for possible filters.

**Comment by balwierz** [comment]
I used `fanc fragments` with 
 - restriction enzyme option
 - keep only chromosomes names and no contigs.
It is much faster. Thanks

Submitted the result bed file to `fanc auto` as `-g` argument

**Comment by kaukrise** [comment]
I have implemented a slightly different parallelisation strategy in `0.8.20`, which bundles smaller chromosomes and/or contigs before sending to a worker. This should eliminate the need for "genome cleaning", at least for the binning step. In case you try this out, please let me know how it worked for you. I tested with a number of different genome sizes and contig counts, but you scenario may differ. Thanks!

**Comment by balwierz** [comment]
Great, thank you very much!
