### ISSUE TITLE
normalization before fanc pca

### ISSUE THREAD

**Issue by biozzq** [vaquerizaslab/fanc#32]
Dear @kaukrise 

Should the hic files be binning (e.g. by any specific resolution), filtered (e.g. by setting `FILTER_LOW_COVERAGE_RELATIVE`) and normalized (e.g. KR normalization) when running `fanc pca`? Thank you.

Best wishes,
Zheng zhuqing

**Comment by kaukrise** [comment]
Hi there,

### Matrix binning

`fanc pca` requires that all Hi-C files have identical binning. The resolution depends on the quality and sequencing depth of your libraries. If the libraries are good enough, you could even use fragment-level Hi-C objects. However, you will generally get more reliable results al lower resolutions (see below)

### Matrix filtering

If you are working with FAN-C files, we generally recommend filtering by low coverage before normalisation, as poorly mappable bins can lead to artefacts. With other pipelines similar filtering steps may have been performed. However, this is not a strict requirement of `fanc pca`.

### Matrix normalisation

You will get more robust results with normalised matrices than with raw counts. We recommend ICE or KR norm. `fanc pca` also scales matrices automatically to the same sequencing depth. When are using the FAN-C pipeline for matrix generation with default settings for normalisation, matrix entries can be interpreted as contact probabilities, in which case you can switch off scaling using `-S`.

### PCA filtering

When running `fanc pca` with default settings for the first time results can often be unexpected. `fanc pca` by default uses the top 50,000 pixels that have the highest variance among input matrices. Without additional parameters, these 50,000 pixels are selected from all intra-chromosomal pixels in the matrix. For high-resolution matrices, pixels representing contacts among distal regions are often very noisy, and therefore can contribute a lot the the overall variance. As a consequence, your PCA will mostly be based on noise. We therefore strongly recommend using the `--max-distance` parameter to set a limit on region distance, so that only informative pixels are considered for the PCA. It often also makes sense to set a `--min-distance` to exclude contacts directly along the matrix diagonal, which mostly represent linear proximity.

You can further filter pixels for information content by using the `--expected-filter` parameter, which ensures that at least one matrix has a signal stronger than the expected value for the pixel at that distance. However, whether this setting makes sense in your data depends on the types of differences you expect in your matrix.

I would encourage you to experiment with low resolution matrices and the different parameters until you find parameter ranges that give robust results!

I hope this helps!

Kai
