### ISSUE TITLE
Does fanc works on Dnase Hic or Microc?

### ISSUE THREAD

**Issue by chenggang108** [vaquerizaslab/fanc#41]
Hi 

A quick question. Can FAN-C process fastq file from Dnase Hic or MicroC data that do not has restriction enzyme cutting sites?

Thanks

Gang

**Comment by kaukrise** [comment]
Yes, that is in principle possible. I haven't personally worked with Micro-C data, but I know that @liz-is has, she will likely be able to provide better input than me! 

My suggestion would be to create a custom bin/restriction map with evenly-spaced bins (I think 100bp is a good start) and use that instead of a restriction enzyme in the FAN-C commands:

```
fanc fragments /path/to/genome.fasta 100 micro_c_bins.bed
```

`micro_c_bins.bed` can then be used, for example, as the `--restriction-enzyme` argument of `fanc auto`.

**Comment by liz-is** [comment]
Yes, I have done this. I started with 100bp bins as Kai suggested and used this as the `--genome` argument to `fanc auto` or `fanc pairs`. I then used `--filter-inward 50 --filter-outward 50 ` to filter inward/outward facing read pairs that align to fragments within 50 bp of each other (i.e. to the same or adjacent fragments). I found that KR normalisation had very high memory requirements for 100bp or 500bp binned Hi-C matrices, so I used ICE normalisation (`--normalise --norm-method ice `). Apart from that, I think everything else used basically default parameters. 

If you want to see how the analysis looked in practice, you can check out [the Snakemake workflow](https://github.com/vaquerizaslab/Ing-Simmons_et_al_dorsoventral_3D_genome/blob/main/workflow/micro-c.smk) (this repo is associated with a forthcoming paper).

**Comment by kaukrise** [comment]
Ow wow, @liz-is , the Snakemake pipeline is a great resource, thanks for sharing it!

**Comment by chenggang108** [comment]
Thank you  liz-is and kaukrise , 

I will try it.

Gang
