### ISSUE TITLE
Second eigenvector extraction

### ISSUE THREAD

**Issue by mdozmorov** [vaquerizaslab/fanc#44]
I'm using `fanc compartments` to extract eigenvectors. Sometimes, one needs the second eigenvector. So, I run the following command:
````
# Resolution
RESOLUTION="1m"
# Eigenvector index
EIGINDEX=2

fanc compartments --domains ${DIROUT}/AB_SAMPLE1_${RESOLUTION}_${EIGINDEX}.bed \
				  --eigenvector ${DIROUT}/AB_SAMPLE1_ev_${RESOLUTION}_${EIGINDEX}.bed \
				  --eigenvector-index $EIGINDEX \
				  --genome $GENOME \
				  ${DIRIN}/SAMPLE1.hic@${RESOLUTION} ${DIROUT}/AB_SAMPLE1_${RESOLUTION}_${EIGINDEX}.ab
````
Extracting the first eigenvector works fine, at 1Mb or 10kb resolutions. But when I try to extract the second eigenvector, the jobs fail. Errors are different, sometimes memory issue (with 10kb, but all worked fine for the first eigenvector), sometimes various Python errors. Any suggestions what to do?

One of the errors is:
````
Traceback (most recent call last):
  File "/home/username/miniconda3/envs/fanc/bin/fanc", line 127, in <module>
    Fanc()
  File "/home/username/miniconda3/envs/fanc/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/home/username/miniconda3/envs/fanc/lib/python3.7/site-packages/fanc/commands/fanc_commands.py", line 3937, in compartments
    eigenvector=ev_index, force=recalculate)
  File "/home/username/miniconda3/envs/fanc/lib/python3.7/site-packages/fanc/architecture/compartments.py", line 210, in eigenvector
    ab_vector = v[:, eigenvector]
  File "/home/username/miniconda3/envs/fanc/lib/python3.7/site-packages/fanc/matrix.py", line 2740, in __getitem__
    out = np.ma.MaskedArray.__getitem__(self, index)
  File "/home/username/miniconda3/envs/fanc/lib/python3.7/site-packages/numpy/ma/core.py", line 3225, in __getitem__
    dout = self.data[indx]
IndexError: index 1 is out of bounds for axis 1 with size 1
````

**Comment by liz-is** [comment]
Hi there,

I've seen this error before when running `fanc compartments` on very small chromosomes/scaffolds. If you only have one valid bin on the chromosome, it'll have a 1x1 matrix which only has one eigenvector by definition. You can avoid this by using the `--exclude-chromosomes` parameter to exclude very small chromosomes, or by subsetting your Hi-C data using `fanc subset` to only include the main chromosomes. I actually typically use only the main chromosomes when constructing the pairs object, because many small scaffolds can often cause issues!

Having said that, it would be ideal if `fanc compartments` returned NA, or issued an informative warning, in these cases. I think @kaukrise might have already implemented this after we came across this issue before?

**Comment by mdozmorov** [comment]
Thank you. The `fanc subset` command gives:
````
fanc subset: error: Cannot use subset on Juicer or Cooler files. Use FAN-C format if you want to subset.
````
The [fanc subset documentation](https://fan-c.readthedocs.io/en/latest/fanc-executable/fanc-generate-hic/fanc_helpers.html#fanc-subset-create-hic-objects-by-subsetting) says "input | Input Hic file." I've even tried `SAMPLE1.hic@1m`, still doesn't work.

I cannot find the documentation for `fanc format`, or for `fanc from-juicer`. Any suggestions?

**Comment by kaukrise** [comment]
Hi,

thanks @liz-is for jumping in! @mdozmorov here are two options for you:

First, I made a new beta version of the compartment calculation which should work in your case. I tested it on some dummy data with a small chromosome and it emits a warning and then sets EV values for that chromosome to `NaN`, as @liz-is suggested:

[fanc-0.9.15b1.tar.gz](https://github.com/vaquerizaslab/fanc/files/5924437/fanc-0.9.15b1.tar.gz)

Please let me know if it also works on your data!

If you want to convert your Juicer file to FAN-C, you can use the following workaround:

```
fanc hic --deepcopy <juicer file> <fanc file>
```

However, this might be slow, depending on the size of your matrix and your local setup.

**Comment by mdozmorov** [comment]
Thanks all, I'll try that soon, swamped for the moment.

**Comment by mdozmorov** [comment]
The new beta version worked better. I could install it and find a way to make it work. Some notes/questions: fan-c doesn't seem to support Juicer's .hic files well - one needs to format them into fan-c .hic format - is that correct? Any information about differences? This command worked to reformat Juicer's .hic:
````
fanc hic --bin-size $RESOLUTION --chromosomes X Y M --norm-method KR --threads 16 --deepcopy juicer.hic@$RESOLUTION fanc.hic
````
Then, `fanc compartments` extracts first and second eigenvectors from `fanc.hic`.

What didn't work: `fanc subset` gives an error: `fanc subset: error: Cannot use subset on Juicer or Cooler files. Use FAN-C format if you want to subset.` But the `fanc format` seems either depreciated or nonexistent.

Some notes on help message for the `fanc hic -h` command: `--subset` argument has a missing space in `contactswithin chromosome 1`. ` --deepcopy` argument is incomplete, ends with `Can be used`. 

The last question - what normalization method would be appropriate before running `fanc compartments`?

Closing as resolved. Thanks, @kaukrise , @liz-is for your help!

**Comment by kaukrise** [comment]
Hi,

thanks for the feedback.

First, can you please let me know what issues you encountered when using Juicer files directly? I tested `fanc compartments` on a Juicer `.hic` file directly and it worked without issues. There should be no need to convert to FAN-C Hi-C format first.

Second, in the command you posted you are doing multiple things, and I am not sure all of those are intended:

1. Copy the Juicer file to FAN-C Hi-C format at `$RESOLUTION` resolution
2. Re-bin the resulting FAN-C file at the same resolution, which is unnessecary
3. Set the normalisation method to `KR` using `--norm-method KR`, but this has no effect, since you did not actually apply the normalisation with `-n`. In any case the bias vector from the Juicer file is copied, and re-normalisation should not be necessary
4. Subset the binned file to chromosomes X, Y, and M

If you still need to convert and subset, you could simply do

```
fanc hic --deepcopy --subset X,Y,M juicer.hic@$RESOLUTION fanc.hic
```

Third, the help text is not supposed to imply that there is a `fanc format` command, but that you should use the FAN-C Hi-C file format.

Fourth, thanks for mentioning the help text issues, I'll fix them.

And finally, ICE norm or KR norm (default in Juicer) should both work fine.

**Comment by kaukrise** [comment]
Actually, I just checked and the `--deepcopy` help text looks fine to me. Not sure what the issue is in your case:

```
  --deepcopy            Deep copy Hi-C file. Copies a Hi-C file to FAN-C
                        format by duplicating individual bins, pixels, and
                        bias information. Can be used to upgrade an existing
                        FAN-C file with an older version or to convert Cooler
                        or Juicer files to FAN-C format.
```

**Comment by mdozmorov** [comment]
Thanks, @kaukrise, it is more clear now. The problem with the original Juicer .hic files is the presence of small chromosomes, on which `fanc compartments` breaks when calculating the second eigenvector. There's `-r, --region` argument, but it is not well documented (need some example) and I was unable to use it. The simplified `fanc hic --deepcopy` with `--normalise` argument should work.

The new beta version of `fanc compartments` still breaks. I saw the message `WARNING Cannot extract EV 1 from chromosome M, because it is too small. Setting EV values on this chromosome to NaN`,  but the error is: `IndexError: index 51 is out of bounds for axis 0 with size 51`.

Last note - `--deepcopy` help looks like this for me, 
![image](https://user-images.githubusercontent.com/864945/107865839-9f041180-6e38-11eb-9ffa-c84adc16cf41.png)

And, for the beta version, help doesn't work at all - `Illegal instruction (core dumped)`. Commands run fine.

**Comment by kaukrise** [comment]
Hi again,

I'd like to resolve the `IndexError` issue you've encountered, but I need more information. Could you please send me the exact command you used (you can obscure pathnames and any other sensitive information, of course), and the complete logging output? At the moment I don't know where in the code the error is actually happening.

I tried the help text with three different systems now and it displays fine on all of them. It looks to me like this is something specific to your setup, like terminal formatting or architecture. As an alternative, you can also use the [online help](https://fan-c.readthedocs.io/en/latest/fanc-executable/fanc-generate-hic/fanc_modular_steps.html#fanc-hic-generating-binning-and-filtering-hic-objects), which also displays the text properly.

The `Illegal instruction (core dumped)` error also indicates an issue with your architecture. Without knowing the specifics of your setup, it is hard for me to debug, but this may be due to one of the FAN-C imports. You could start by importing the [FAN-C dependencies](https://github.com/vaquerizaslab/fanc/blob/main/setup.py) on by one in a Python console to see if you can trace down the culprit, something like this:

```
import numpy
import scipy
import pillow
# ...
```

and so on, line by line.

And, just to mention this again: Juicer files are typically already KR normalised, and FAN-C copies that normalisation during `--deepcopy`, so there should be no need to normalise the matrix again with `--normalise` - unless you prefer the FAN-C normalisation because it expresses pixel values as contact probabilities?

Cheers,
Kai

**Comment by mdozmorov** [comment]
I couldn't reproduce that exact error. Tried twice with supposedly the settings that generated it. But the code generates another one. I use:
````
fanc hic --deepcopy ${DIRIN}/${FILEIN}.hic@${RESOLUTION} ${FILEOUT}.hic

fanc compartments --domains ${DIROUT}/AB_${FILEOUT}_dm_${EIGINDEX}.bed \
                  --eigenvector ${DIROUT}/AB_${FILEOUT}_ev_${EIGINDEX}.bed \
                  --enrichment-profile enrichment_${FILEOUT} \
                  --eigenvector-index $EIGINDEX \
                  --genome $GENOME \
                  ${FILEOUT}.hic ${DIROUT}/AB_${FILEOUT}_${EIGINDEX}.ab
````
Here's the full log. The job completes successfully, there are warning messages at the end, the results are generated for all autosomes, X, Y, and even M (with nan).
[fancABtest.txt](https://github.com/vaquerizaslab/fanc/files/5977726/fancABtest.txt)

I'll monitor the output logs, will let know if encounter that `IndexError` again.
