### ISSUE TITLE
Attribute error with fanc.hic LowCoverageFilter

### ISSUE THREAD

**Issue by mphan236** [vaquerizaslab/fanc#47]
Hi Kai, 

I wanted to do some downstream analyse for Juicer-generated .hic files using your FANC python API (nice name, btw). 

As suggested in your documentation, I was trying to filter my 5kb binned .hic using LowCoverageFilter. This took a while to run, and then python threw an Attribute error:

AttributeError                            Traceback (most recent call last)
<ipython-input-7-fac3f6cf3855> in <module>
      1 h22 = fanc.load("./inter_30.hic@5000")
      2 low_cov_filt = LowCoverageFilter(h22, rel_cutoff = 0.25)
----> 3 h22.filter(low_cov_filt)
      4 h22.run_queued_filters()

AttributeError: 'JuicerHic' object has no attribute 'filter'

Any idea where I might have gone wrong? I'm using fanc 0.9.1 in a conda env with python 3.7.5.

Thanks a lot!

Mikie

**Comment by kaukrise** [comment]
Hi there,

unfortunately Juicer files are incompatible with FAN-C filters. FAN-C treats the files as read-only, because the file structure is very different from the FAN-C format.

You could convert the file to FAN-C format before filtering, for example using the command line tool:

```bash
fanc hic --deepcopy <juicer.hic@5kb> <fanc.hic>
```

This could take a while at 5kb, but then your above sequence of commands should work.

Also, if possible, I'd recommend upgrading to the latest version of FAN-C using `pip` - there have been numerous bug fixes and improvements since version `0.9.1` was released. Unfortunately, getting a new version onto Bioconda has proven quite difficult due to dependency issues.

Cheers,
Kai
