### ISSUE TITLE
Loop aggregate (brighter corner + loop strength)

### ISSUE THREAD

**Issue by rdacemel** [vaquerizaslab/fanc#48]
First of all thanks for the amazing resource FANC is.

I am performing some loop aggregates on the Bonev 2017 data I am a bit confused with the results. I assume it is normal that one of the four corners of the heatmap it's brighter, in principle the one that correspond to the "inner" part of the loop closer to the diagonal. However, when I retrieve the matrices such corner is the upper-right corner while in your publications it shows as the bottom-left one (which I think it's much more intuitive). Is there a way to figure out what is happening? Can I just flip it, or there is something wrong in my code that is more profound?

Also, I think I've noticed that the loop strength calculation has been placed in legacy, is there a way to make use of it still from the latest version? Is it problematic in some sense? 

Thanks a lot!

Rafa.

**Comment by kaukrise** [comment]
Hi, thank you very much for your kind feedback!

I apologise for the confusion, there has been some internal debate and back and forth about whether to use loop regions from the upper or lower triangular matrix, and if my memory serves me right, it probably changed after we prepared the figures for the manuscript. After a quick review of the code shows that we are using the lower triangular in the current version. So, yes, just flip it if you prefer the upper triangular version.

There are actually two main causes for signal increase in one corner: one is the effect of regions closer to the diagonal (the TAD corner from corner loops). The other one happens in the opposite corner and stems from sparse regions of the diagonal, where the O/E matrix overestimates the enrichment. The latter is easily spotted though, because the corner will be entirely red (in the default colour scheme). Since you are working with the Bonev data, yours is almost certainly the TAD corner.

The `loop_strength` function is still in `fanc.architecture.aggregate` - don't use the legacy one. I am on mobile, but once I am back at my desk next week, I can dig up an example for you.

Cheers,
Kai

**Comment by kaukrise** [comment]
Thinking about it a bit more, the location of the corner with higher intensity also depends on how the loops in the file are defined.

I'll run some examples on the Bonev data myself next week and then will update here!

**Comment by rdacemel** [comment]
Thanks a lot for the swift reply! I have the anchors ordered so that the anchor1 always have smaller coords than anchor2. I guess that is the relevant info! :)

**Comment by kaukrise** [comment]
Hey, I'm really sorry, I don't usually leave feedback for so long, but I have a crazy amount of work this week. I'll try to get to it next week!

**Comment by kaukrise** [comment]
Hi, thanks for your patience.

I reviewed the aggregate code and since you mentioned it was counter-intuitive, I thought I'd leave the choice of aggregate plot orientation to the user. So, in version `0.9.15` you can now

- On the command line use the `--lower-triangular-plot` switch to invert the orientation of the loop aggregate plot so it appears as below the diagonal
- In the API, use `lower_triangular=True` in `fanc.plotting.statistics.aggregate_plot` to achieve the same effect

The default is now "upper triangular", as I agree that it is otherwise confusing for people coming from the manuscript and discovering the plot to be inverted, as in your case. And all of this assumes that the diagonal runs from the top left to the bottom right corner, as is the default using `fancplot`.

Finally, regarding the loop strength calculation, here is the promised example:

```python
import fanc
import numpy as np
from fanc.architecture.aggregate import loop_strength

loops = fanc.load("/path/to/loops.bedpe")
hic = fanc.load("/path/to/file.hic")

ls = loop_strength(hic, loops)

# convert to numpy array for convenience
ls = np.array(ls)

# plot
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(2, 2.2))
ax.boxplot([ls], notch=True, widths=0.8, showfliers=False)
ax.set_ylabel('Loop strength')
ax.set_xticklabels(["sample"])
plt.xticks(rotation=90)
fig.tight_layout()
plt.show()
```

**Comment by rdacemel** [comment]
Thanks a lot for carefully revisiting this! Everything is clearer now.

**Comment by kaukrise** [comment]
Great, thank you!
