### ISSUE TITLE
fanc downsample

### ISSUE THREAD

**Issue by mujahida87** [vaquerizaslab/fanc#58]
Hi @kaukrise,
It's actually not an issue but I'm a bit confused about the 'n' representation in fanc downsample command (fanc downsample hic  n  output). can we use the number of valid pairs (e.g: n 25,000,000) that we can to keep in the downsampled hic file or the reference hic file to whom we want to equalize the input file? 

Thank you

**Comment by kaukrise** [comment]
Hi, first of all please use `fanc hic --downsample <n> <input hic> <output hic>` instead of `fanc downsample` (there is a warning message about this, too).

Then `<n>` can be one of three things:

1. An integer, such as `25000000`. In this case, `<input hic>` will be downsampled to 25 million valid pairs
2. A float, such as `0.8`. In this case, `<input hic>` will be downsampled to 80% of its original valid pairs
3. The path to another (reference) Hi-C file. In this case, `fanc` will downsample `<input hic>` so that it contains exactly as many valid pairs as the reference Hi-C file

In each case the downsampled object will be written to `<output hic>`.

Hope that clarifies things! Kai

**Comment by mujahida87** [comment]
Thank you, yes it worked.
