### ISSUE TITLE
plot inter-chromosome contacts

### ISSUE THREAD

**Issue by gorliver** [vaquerizaslab/fanc#85]
Thank you for the tool that makes everything much easier!
I wonder can fancplot plot inter-chromosome contacts? I'm seeking to plot a contact map including the all-vs-all contacts.

**Comment by kaukrise** [comment]
Hi, and thanks for the nice words!

Plotting inter-chromosomal contacts is currently only possible in the Python API. Here is an example using the sample data:

```python
import fanc
import fanc.plotting as fancplot

hic = fanc.load(‘/path/to/file_250kb.hic’)

p = fancplot.SquareMatrixPlot(hic, vmax=0.05)
p.plot(('chr18', 'chr19'))
p.show()
```

There is no functionality available for plotting whole-genome matrices. The reason is that each chromosome is normalised individually by default - as such, each chromosome will be scaled slightly differently, and plotting every chromosome in one image can be misleading - especially if the aim is to compare contacts across chromosomes.

This would not be an issue for whole-genome corrected or uncorrected matrices. If you want to go that way, here is a snippet to get you started:

```python
import fanc
import fanc.plotting as fancplot
import matplotlib.pyplot as plt

hic = fanc.load(‘/path/to/file.hic’)

m = hic.matrix(norm=False)  # get the raw whole-genome matrix
plt.imshow(m, vmax=20, cmap='germany’)
plt.show()
```

Alternatively you could export FAN-C files to Cooler files and use the amazing [HiGlass](https://higlass.io/) for visualisation!

**Comment by gorliver** [comment]
Hi @kaukrise 
Thank you for the codes!
The HiGlass looks very nice and I will try it for sure.
