### ISSUE TITLE
O/E matrix of KR norm generated by FAN-C is different from that extracted from the original Juicer .hic

### ISSUE THREAD

**Issue by wangfuzhou110** [vaquerizaslab/fanc#89]
I was trying to use FAN-C to do some transformations on a Juicer `.hic` file (the GM12878 Hi-C, Rao et al. 2014). First of all, I converted the original file to FAN-C format by:

```
fanc from-juicer --juicer-norm NONE --juicer-tools-jar "juicer.jar" "data/gm12878.hic" "data/hg19.fa" 10000 "data/gm12878.fanc"
```

and then I added KR norm to the `.fanc` file with the following command:

```
fanc hic "data/gm12878.fanc" "data/gm12878.kr.fanc" -n -m KR
```

By this, I believe that the KR norm is applied to each chromosome and expected vectors should also have been generated. To validate it, I used `fanc dump -e -s chr22--chr22 gm12878.kr.fanc corrected_kr_oe.txt` to output the O/E matrix and compared it with the one extracted from the original Juicer `.hic` file using JuicerTool. I expected those matrices similar to each other in terms of entry values. However, the results came out very different -- the O/E matrix generated by FAN-C does not have many NaN values while the Juicer does (the NaN entries in Juicer-generated matrix are float numbers in the FAN-C output), and most numeric values are inconsistent in these files. I am a little bit confused about this behaviour and could you kindly point out if I did anything wrong? 

Furthermore, I would like to downsample the data with 

```
fanc hic "data/gm12878.fanc" "data/gm12878.50.fanc" --downsample "0.5"
```

Is this command correct? I would appreciate it very much if you could let me know if there is anything wrong with that command.

Fuzhou

**Comment by kaukrise** [comment]
Hey, thank you for the questions. First of all, what version of FAN-C are you using? Earlier versions had some issues with Juicer files that have since been resolved.

```
fanc -V
```

Then, the KR norm is added in place, so your command would need to be simply

```
fanc hic -n data/gm12878.fanc
```

(KR norm is the default)

Next, can you please be more specific as to how the O/E values differ from the Juicer file? Some differences might be expected due to the way FAN-C and Juicer handle unmappable regions differently (which would also explain the NAs, perhaps), but they should not be orders of magnitude different.

A plot of the O/E matrix from both the Juicer file and the FAN-C file would be helpful. For example, what do these plots look like?

```
# on Juicer file
fancplot chr18:22mb-23mb -p triangular -e -vmin -2 -vmax 2 data/gm12878.hic@10kb@KR

# on FAN-C file
fancplot chr18:22mb-23mb -p triangular -e -vmin -2 -vmax 2 data/gm12878.fanc
```

The downsampling command looks alright - did you encounter issues with that, too?

**Comment by wangfuzhou110** [comment]
Hi! Thank you for your prompt reply!

The FAN-C version is 0.9.21 -- I pulled it from this repo several days ago and installed it from source. Is this the stable version of FAN-C?

Indeed the matrices are not orders of magnitude different. Here are the first 10 lines of each `.txt` file:

```
# The FAN-C file:
chr22   16050001        16060000        chr22   16050001        16060000        5.674532920289357
chr22   16050001        16060000        chr22   16060001        16070000        1.9466586442451523
chr22   16060001        16070000        chr22   16060001        16070000        2.1443823433650735
chr22   16050001        16060000        chr22   16070001        16080000        9.14569226886038
chr22   16060001        16070000        chr22   16070001        16080000        21.11691852426661
chr22   16210001        16220000        chr22   16210001        16220000        7.618832416692907
chr22   16220001        16230000        chr22   16220001        16230000        0.7834855247687575
chr22   16220001        16230000        chr22   16230001        16240000        3.4424617815506777
chr22   16230001        16240000        chr22   16230001        16240000        1.1038430776332677
chr22   16230001        16240000        chr22   16240001        16250000        21.712556242396797

# The Juicer output:
16050000        16050000        6.026676
16050000        16060000        4.0167055
16060000        16060000        7.085533
16050000        16070000        NaN
16060000        16070000        NaN
16210000        16210000        NaN
16220000        16220000        2.2181985
16220000        16230000        12.095252
16230000        16230000        3.9672282
16230000        16240000        NaN
```

Although they have the same order of magnitude, the values are quite different, and it seems as if the change cannot be modelled by a simple linear transformation.

There are also some entries that are originally NaN become very large values in the FAN-C file, for example:

```
# In FAN-C file:
chr22   50510001        50520000        chr22   51240001        51250000        1201.5975907419381

# In Juicer file:
50510000        51240000        NaN
```

Below are the figures generated by the fancplot commands:

Juicer Matrix:
![juicer](https://user-images.githubusercontent.com/46041002/146978718-e1397fef-2d07-409a-8341-37504352b54a.png)

FAN-C matrix:
![fanc](https://user-images.githubusercontent.com/46041002/146978742-553b3d2a-dd94-4f84-a915-bfb62b2ba2a3.png)

The figures, however, look pretty similar to each other, although there are more "white" regions on the Juicer one?


The downsampling command runs well on my PC, but the memory issue is often encountered. The process keeps being killed after running overnight. I had a look at the source code and found that there is a call to python built-in function `sorted` and this might be the reason for memory overflow. Do you have any suggestions on it?

BTW, may I ask a bit more about the implicit data structure of FAN-C? My thought is that each FAN-C file can incorporate an uncorrected matrix and its corresponding expected vector, and optionally incorporate **one** kind of normalised matrix and the expected vector. Is this correct? It would be very nice of you if you could kindly let me know more about it!

Thank you again,

Fuzhou

**Comment by kaukrise** [comment]
Hi, I think I now figured out what is happening here.

In FAN-C, regions (bins) can be either valid or invalid. Invalid regions are ignored in analyses and masked during plotting. When doing the preprocessing with FAN-C, one step is to mark poorly mappable regions as invalid during filtering. A region's status is stored in a region attribute `valid`, and generally retrieved for a stretch of regions using the `hic.mappable` function.

Of course, Juicer files do not have region annotations, so the "usual" way FAN-C determines a region's validity does not work here. However, it turns out that Juicer does something very similar to masking by setting the normalisation vector entry of an "invalid" region to `NaN` - FAN-C uses that information instead for the `hic.mappable` function or `region.valid` property.

When you copied the Juicer file to a FAN-C file you explicitly disabled normalisation (`--juicer-norm NONE`). Since the Juicer normalisation vector contains region validity information, this was also lost in the FAN-C copy. This is very likely why you are seeing values in the FAN-C copy where there are `NaN` in the Juicer file. This would also explain why you are seeing discrepancies in values close to poorly mappable regions (such as the ends of chromosomes as in your example), as bins with a sparse number of reads inflate counts during normalisation. It also generally affects the expected value calculation, since the mean counts at each distance will be influenced by previously invalid regions (and the inflated counts would make their effect stronger).

What can you do about this? My first suggestion would be to try copying the Juicer file keeping the `KR` normalisation enabled. This should properly "ignore" NaN regions. If you want, you can still re-normalise the same way as before, since the bias vector is stored independently of the raw counts, but why not just keep the Juicer KR vector? Alternatively, you can try filtering for low coverage on the FAN-C file you already have (`fanc hic --low-coverage-auto`, for example, or do a marginals plot first and choose a cutoff for low coverage manually), which should also mitigate the effect you are seeing. This should get you a lot closer to the Juicer O/E values (although you probably won't get 100% identity in either case).

Regarding your other questions:

I already tried to make `fanc downsample` somewhat memory efficient - the matrix is never loaded into memory, for example. As far as I can see, the `choice` array should be the largest data structure kept in memory. It is possible that calling `sorted` on the array uses a lot of memory - would you have a suggestion how to improve this? Just for completeness: how much memory are you working with?

Finally, your explanation of the FAN-C data structure is almost correct. It stores:

- Region information (chromosome, start, end, valid, and potentially other annotations)
- The raw matrix in sparse format for a single resolution
- The matching normalisation / bias vector to correct the matrix on the fly
- The matching expected value vectors (one per chromosome). By default this is calculated only for the normalised matrix, but is automatically calculated for the raw matrix if requested.

**Comment by wangfuzhou110** [comment]
Dear Kai @kaukrise ,

Thank you for answering these questions. I will try enabling KR norm when copying the Juicer file and get you updated when the process finishes.

For `fanc downsample`, since `choice` is a NumPy array, my suggestion is to use `ndarray.sort` instead, which performs an in-place sort on a NumPy `ndarray` object. I've tried this on my 64 GB RAM PC and the memory issue is addressed. What do you think?

FAN-C is indeed well-designed software and is a very helpful tool. Thank you for developing it!

**Comment by wangfuzhou110** [comment]
Hi, I tried converting the Juicer file to FAN-C format with KR norm enabled and those NaN entries were ignored as expected, but another issue was encountered: When I used `fanc dump -u` and `fanc dump` to extract the interactions from the FAN-C file, both commands output exactly the same results:


```
# head test.txt
chr22   16050001        16060000        chr22   16050001        16060000        12441.519
chr22   16050001        16060000        chr22   16060001        16070000        2348.355
chr22   16060001        16070000        chr22   16060001        16070000        14627.431
chr22   16220001        16230000        chr22   16220001        16230000        4579.2666
chr22   16220001        16230000        chr22   16230001        16240000        7071.453
chr22   16230001        16240000        chr22   16230001        16240000        8189.977
chr22   16340001        16350000        chr22   16340001        16350000        10296.51
chr22   16220001        16230000        chr22   16350001        16360000        2062.5073
chr22   16340001        16350000        chr22   16350001        16360000        1030.9113
chr22   16350001        16360000        chr22   16350001        16360000        11147.469
```

As is described in the documentation, with `-u` the command is supposed to output the raw matrix, but in this case it seems that this option does not take effect?

The command converting Juicer file to FAN-C file is:
```
fanc from-juicer --no-inter-chromosomal --juicer-norm KR --juicer-tools-jar "juicer.jar" "data/gm12878.hic" "data/hg19.fa" 10000 "data/gm12878_100.fanc"

```

**Comment by kaukrise** [comment]
You are absolutely right. I wrote the `from-juicer` function before FAN-C had full Juicer file support, so it used an outdated API. I will fix this in the next version, but essentially I am going to replace the function with a deep copy, so could you please try this?


```
fanc hic --deepcopy "data/gm12878.hic@10000@KR" "data/gm12878_10kb.fanc"
```

I tested this with a local Juicer file and this worked fine.

**Comment by wangfuzhou110** [comment]
Thank you for illustrating that. Deepcopy worked for me as well. However the values of O/E matrix are not identical to the original Juicer file's, but I think maybe it is due to the difference between the ways of calculating expected vectors? Does FAN-C adopt the same expected value calculation scheme as Juicer?

```
# The FAN-C file:
22      16050001        16060000        22      16050001        16060000        3.943763963351473
22      16050001        16060000        22      16060001        16070000        2.4398410513115825
22      16060001        16070000        22      16060001        16070000        4.636663345411113
22      16220001        16230000        22      16220001        16230000        1.4515547686209394
22      16220001        16230000        22      16230001        16240000        7.346939232836385
22      16230001        16240000        22      16230001        16240000        2.5960927373982847
22      16340001        16350000        22      16340001        16350000        3.2638301271036774
22      16220001        16230000        22      16350001        16360000        18.580225153431893
22      16340001        16350000        22      16350001        16360000        1.0710729567862611
22      16350001        16360000        22      16350001        16360000        3.53357071409675
```

```
# The Juicer file:
16050000	16050000	6.026676
16050000	16060000	4.0167055
16060000	16060000	7.085533
16050000	16070000	NaN
16060000	16070000	NaN
16210000	16210000	NaN
16220000	16220000	2.2181985
16220000	16230000	12.095252
16230000	16230000	3.9672282
16230000	16240000	NaN
```

**Comment by kaukrise** [comment]
Hey, I'm currently on holiday, so I don't have time to reply in depth.

FAN-C calculates the mean of contacts at a fixed distance as expected value. For this, every invalid region is carefully excluded, so as to not bias the expected value.

I don't know how Juicer handles the calculation internally, especially with regards to NaN and invalid regions. If I remember correctly from the original manuscript, there was also some smoothing of the expected value curve involved, but I don't know if that is part of the O/E calculation in Juicer. These are the main differences I can think of right now.

**Comment by wangfuzhou110** [comment]
Hey, I did not read the thread these days. Sorry about this delayed reply.

I imagine the difference should be caused by some trivial things? In fact, the O/E matrix of the deep-copied FAN-C file is not really used in my research, though -- the downsampled files are only sampled from the raw entries if I understand correctly. Hence, I believe that FAN-C can correctly calculate the expected vectors for the downsampled objects, but I am merely curious about the causes of such differences.
